### ISSUE TITLE
Add support for Python 3.4

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#15]
We get the following build error in Travis when building for 3.4:

```
Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /home/travis/virtualenv/python3.4.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6ji57j2r/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptmrhzy74pip-wheel- --python-tag cp34:
  running bdist_wheel
  /home/travis/virtualenv/python3.4.6/bin/python /tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py
  LLVM version... 5.0.0git-929163d
  
  Traceback (most recent call last):
    File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 167, in <module>
      main()
    File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 157, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 119, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 6.0.x. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/home/travis/virtualenv/python3.4.6/bin/python' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built kapre resampy librosa future numba audioread pycparser
Failed to build llvmlite
Installing collected packages: scipy, keras, audioread, scikit-learn, joblib, decorator, llvmlite, numba, resampy, librosa, future, kapre, pycparser, cffi, PySoundFile, openl3
  Running setup.py install for llvmlite ... error
    Complete output from command /home/travis/virtualenv/python3.4.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6ji57j2r/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ocnebo16-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.4.6/include/site/python3.4/llvmlite:
    running install
    running build
    got version from file /tmp/pip-build-6ji57j2r/llvmlite/llvmlite/_version.py {'version': '0.25.0', 'full': '9af98a608a49278dbc4ce5dc743152f2341b6a87'}
    running build_ext
    /home/travis/virtualenv/python3.4.6/bin/python /tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py
    LLVM version... 5.0.0git-929163d
    
    Traceback (most recent call last):
      File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 167, in <module>
        main()
      File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 157, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-6ji57j2r/llvmlite/ffi/build.py", line 119, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 6.0.x. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/home/travis/virtualenv/python3.4.6/bin/python' failed with exit status 1
    
    ----------------------------------------
Command "/home/travis/virtualenv/python3.4.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6ji57j2r/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ocnebo16-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.4.6/include/site/python3.4/llvmlite" failed with error code 1 in /tmp/pip-build-6ji57j2r/llvmlite/
The command "pip install -e .[tests]" failed and exited with 1 during .
Your build has been stopped.
```

Towards getting an MVP out, we'll ignore 3.4 for now and revisit at some point in the future.

**Comment by justinsalamon** [comment]
Unless users come clamoring with requests for 3.4 support, I'd argue we can close this one out.
