### ISSUE TITLE
API docs broken

### ISSUE THREAD

**Issue by auroracramer** [marl/openl3#71]
ReadTheDocs build passed, but silently failed :cold_sweat: 
```
WARNING: autodoc: failed to import module u'core' from module u'openl3'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/openl3/envs/stable/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openl3/checkouts/stable/openl3/__init__.py", line 3, in <module>
    from .core import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/openl3/checkouts/stable/openl3/core.py", line 10, in <module>
    from .models import load_audio_embedding_model, load_image_embedding_model, _validate_audio_frontend
  File "/home/docs/checkouts/readthedocs.org/user_builds/openl3/checkouts/stable/openl3/models.py", line 42
    def get_spectrogram(*a, return_decibel=False, **kw):
                                         ^
SyntaxError: invalid syntax
```

It looks to be an issue of ReadTheDocs using Python 2.x instead of 3.x.

```
WARNING: autodoc: failed to import module 'core' from module 'openl3'; the following exception was raised:
No module named 'tensorflow.keras'; 'tensorflow' is not a package
```

^ Also seems to be because it's not mocked in docs/conf.py

**Comment by auroracramer** [comment]
Closed by #72
