### ISSUE TITLE
Error installing openl3 on Win64 with Python 3.10

### ISSUE THREAD

**Issue by rjungbeck** [marl/openl3#94]
When installing openl3 with pip I get the following error:

    wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
      scikit-image>=0.14.3librosa>=0.7.2
'

**Comment by auroracramer** [comment]
Currently, only Python 3.6, 3.7, and 3.8 are supported. We'll have to do some updates at some point to deal with the new PyPI packaging conventions.

**Comment by jonnor** [comment]
What are the known issues with Python 3.10 support?

I might be interested in trying to address them, as we are transitioning from Python 3.8 to 3.10

**Comment by rjungbeck** [comment]
I am already stuck in installation. So I can't tell you whats happening later.

**Comment by jtcramer** [comment]
Oh whoops also this specific issue is due to a typo in `setup.py`. The latest version should address this.

**Comment by jtcramer** [comment]
> What are the known issues with Python 3.10 support?
> 
> I might be interested in trying to address them, as we are transitioning from Python 3.8 to 3.10

The issue that I've seen people facing seem to be a difference in how PyPI packaging metadata is defined. I haven't caught up yet with whatever changes they may have made yet.

**Comment by oykuthejedi** [comment]
I am using Python version 3.12 and encountered problems with the installation.

**Comment by braviadev** [comment]
I am using Python version 3.12 and encountered problems with the installation.

Collecting openl3
  Using cached openl3-0.4.2.tar.gz (29 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\O\AppData\Local\Temp\pip-install-7s3m_jd7\openl3_bf932f29c03e484db36343350a1de00c\setup.py", line 4, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


Didnt you want to continue the project again, please brief us so that we can know what to do next.
